import gql from "graphql-tag";
export default gql(`
query getRequestById($requestId:UUID!){
  tblRequestByRequestId(requestId:$requestId ){
    nodeId
    requestId
    serviceCategory
    title
    description
    userId
    locationTitle
    latitude
    longitude
    isHealthcare
    isCareSubscription
    isDisabled
    isCompleted
    serviceNeedsOn
    serviceEndsOn
    advanceAmount
    payableOnCompletion
    total
    paymentDue
    isDateFlexible
    isActive
    status
    userFeedback
    providerFeedback
    createdAt
    updatedAt
    deletedAt
     tblUserReactionsByRequestId{
      totalCount
      nodes{
        requestId
        reactionId
        providerId
        isLiked
        isDisliked
        isVisible
        userId
        updatedAt
        createdAt
      }
    }
    tblChatsByRequestId(condition:{chatInititated:true}){
      totalCount
    }
    tblServiceOrdersByRequestId{
      nodes{
        serviceOrderId
        providerId
        orderStatus
      }
      totalCount
    }
    tblUserByUserId{
      userId
      phoneNumber
      countryCode
      username
      fullname
      avatarUrl
      aboutme
      city
      state
      email
      country
    }
  }
}`);