steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-t',
      '$_IMAGE_NAME:$COMMIT_SHA',
       '.',
      '--build-arg',
       'value=${_ENV_MODE}',
      '--build-arg',
       'exposeportvalue=${_ENV_EXPOSE_PORT}',
       '-f',
       $_DOCKERFILE_NAME
    ]

    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--output=output'
    id: Prepare deploy
    timeout: '1600s'
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
        fi
    id: Save configs
    entrypoint: sh
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    timeout: '1600s'
    id: Apply deploy
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
timeout: 1660s
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_LABELS: ''
  _IMAGE_NAME: gcr.io/rytzee/yoco-frontend
  _K8S_YAML_PATH: kubernetes/deployment.yml
  _DOCKERFILE_NAME: Dockerfile
  _OUTPUT_BUCKET_PATH: yoco_cloudbuild/deploy
  _K8S_NAMESPACE: default
  _GKE_CLUSTER: rytzee-cluster
  _DOCKERFILE_DIR: ''
  _GKE_LOCATION: us-central1-c
  _K8S_ANNOTATIONS: gcb-trigger-id=96032f23-ed85-444e-96ef-17088607b24c
  _K8S_APP_NAME: yoco-frontend
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME