import gql from "graphql-tag";
export default gql(`
query getCareByRequestId($requestId:UUID!){
    allTblCarePackages(condition:{
      requestId:$requestId
    }){
      nodes{
        careId,
        careTitle,
        careDescription,
        paymentTerms,
        billingDate,
        requestId,
        userCurrency,
        optedMtp,
        status,
        userId,
        mtpFee,
        crvFee,
        noOfMtp,
        noOfCrv,
          tblPackagePricingsByCareId{
           nodes{
            priceId,
            priceItem,
            amount,
          }
        },
        tblCareProvidersByCareId{
          nodes{
            providerId,
            careProviderId,
            tblUserByProviderId{
              userId,
              username,
              email,
              fullname,
              avatarUrl,
              aboutme,
              phoneNumber,
              countryCode,
              title,
              spiffy,
              tblEmploymentsByUserId(orderBy:FROM_YEAR_DESC){
                nodes{
                  employmentId
                  jobTitle
                  companyName
                  fromYear
                  toYear
                  description
                }
              }
              tblEducationsByUserId(orderBy:FROM_YEAR_DESC){
                nodes{
                  educationid
                  degreeTitle
                  college
                  toYear
                  fromYear
                  createdAt
                }
              }
              tblUserLocationByUserId{
                longitude
                latitude
              }
            }
            supportDescription,
            briefDescription,
            yocoComments,
            monthlyFee,
            perVisitCharge,
            noOfVisits,
            visitType,
            providerFee,
            yocoServiceCharge,
            totalAmountInr,
            currnecyType,
            currencyRate,
            totalAmountByUser,
            careProviderId,
            
          }
        }
        
      }
        totalCount
    }
  }`);