export const countries = [
    { country: "AFGHANISTAN", currency: "AFN" },
    { country: "ALBANIA", currency: "ALL" },
    { country: "ALGERIA", currency: "DZD" },
    { country: "AMERICAN SAMOA", currency: "USD" },
    { country: "ANDORRA", currency: "EUR" },
    { country: "ANGOLA", currency: "AOA" },
    { country: "ANGUILLA", currency: "XCD" },
    { country: "ANTIGUA AND BARBUDA", currency: "XCD" },
    { country: "ARGENTINA", currency: "ARS" },
    { country: "ARMENIA", currency: "AMD" },
    { country: "ARUBA", currency: "AWG" },
    { country: "AUSTRALIA", currency: "AUD" },
    { country: "AUSTRIA", currency: "EUR" },
    { country: "AZERBAIJAN", currency: "AZN" },
    { country: "BAHAMAS (THE)", currency: "BSD" },
    { country: "BAHRAIN", currency: "BHD" },
    { country: "BANGLADESH", currency: "BDT" },
    { country: "BARBADOS", currency: "BBD" },
    { country: "BELARUS", currency: "BYN" },
    { country: "BELGIUM", currency: "EUR" },
    { country: "BELIZE", currency: "BZD" },
    { country: "BENIN", currency: "XOF" },
    { country: "BERMUDA", currency: "BMD" },
    { country: "BHUTAN", currency: "BTN" },
    { country: "BHUTAN", currency: "INR" },
    { country: "BOLIVIA (PLURINATIONAL STATE OF)", currency: "BOB" },
    { country: "BOLIVIA (PLURINATIONAL STATE OF)", currency: "BOV" },
    { country: "BONAIRE, SINT EUSTATIUS AND SABA", currency: "USD" },
    { country: "BOSNIA AND HERZEGOVINA", currency: "BAM" },
    { country: "BOTSWANA", currency: "BWP" },
    { country: "BOUVET ISLAND", currency: "NOK" },
    { country: "BRAZIL", currency: "BRL" },
    { country: "BRITISH INDIAN OCEAN TERRITORY (THE)", currency: "USD" },
    { country: "BRUNEI DARUSSALAM", currency: "BND" },
    { country: "BULGARIA", currency: "BGN" },
    { country: "BURKINA FASO", currency: "XOF" },
    { country: "BURUNDI", currency: "BIF" },
    { country: "CABO VERDE", currency: "CVE" },
    { country: "CAMBODIA", currency: "KHR" },
    { country: "CAMEROON", currency: "XAF" },
    { country: "CANADA", currency: "CAD" },
    { country: "CAYMAN ISLANDS (THE)", currency: "KYD" },
    { country: "CENTRAL AFRICAN REPUBLIC (THE)", currency: "XAF" },
    { country: "CHAD", currency: "XAF" },
    { country: "CHILE", currency: "CLF" },
    { country: "CHILE", currency: "CLP" },
    { country: "CHINA", currency: "CNY" },
    { country: "CHRISTMAS ISLAND", currency: "AUD" },
    { country: "COCOS (KEELING) ISLANDS (THE)", currency: "AUD" },
    { country: "COLOMBIA", currency: "COP" },
    { country: "COLOMBIA", currency: "COU" },
    { country: "COMOROS (THE)", currency: "KMF" },
    { country: "CONGO (THE DEMOCRATIC REPUBLIC OF THE)", currency: "CDF" },
    { country: "CONGO (THE)", currency: "XAF" },
    { country: "COOK ISLANDS (THE)", currency: "NZD" },
    { country: "COSTA RICA", currency: "CRC" },
    { country: "CROATIA", currency: "HRK" },
    { country: "CUBA", currency: "CUC" },
    { country: "CUBA", currency: "CUP" },
    { country: "CURAÇAO", currency: "ANG" },
    { country: "CYPRUS", currency: "EUR" },
    { country: "CZECH REPUBLIC (THE)", currency: "CZK" },
    { country: "CÔTE D'IVOIRE", currency: "XOF" },
    { country: "DENMARK", currency: "DKK" },
    { country: "DJIBOUTI", currency: "DJF" },
    { country: "DOMINICA", currency: "XCD" },
    { country: "DOMINICAN REPUBLIC (THE)", currency: "DOP" },
    { country: "ECUADOR", currency: "USD" },
    { country: "EGYPT", currency: "EGP" },
    { country: "EL SALVADOR", currency: "SVC" },
    { country: "EL SALVADOR", currency: "USD" },
    { country: "EQUATORIAL GUINEA", currency: "XAF" },
    { country: "ERITREA", currency: "ERN" },
    { country: "ESTONIA", currency: "EUR" },
    { country: "ETHIOPIA", currency: "ETB" },
    { country: "EUROPEAN UNION", currency: "EUR" },
    { country: "FALKLAND ISLANDS (THE) [MALVINAS]", currency: "FKP" },
    { country: "FAROE ISLANDS (THE)", currency: "DKK" },
    { country: "FIJI", currency: "FJD" },
    { country: "FINLAND", currency: "EUR" },
    { country: "FRANCE", currency: "EUR" },
    { country: "FRENCH GUIANA", currency: "EUR" },
    { country: "FRENCH POLYNESIA", currency: "XPF" },
    { country: "FRENCH SOUTHERN TERRITORIES (THE)", currency: "EUR" },
    { country: "GABON", currency: "XAF" },
    { country: "GAMBIA (THE)", currency: "GMD" },
    { country: "GEORGIA", currency: "GEL" },
    { country: "GERMANY", currency: "EUR" },
    { country: "GHANA", currency: "GHS" },
    { country: "GIBRALTAR", currency: "GIP" },
    { country: "GREECE", currency: "EUR" },
    { country: "GREENLAND", currency: "DKK" },
    { country: "GRENADA", currency: "XCD" },
    { country: "GUADELOUPE", currency: "EUR" },
    { country: "GUAM", currency: "USD" },
    { country: "GUATEMALA", currency: "GTQ" },
    { country: "GUERNSEY", currency: "GBP" },
    { country: "GUINEA", currency: "GNF" },
    { country: "GUINEA-BISSAU", currency: "XOF" },
    { country: "GUYANA", currency: "GYD" },
    { country: "HAITI", currency: "HTG" },
    { country: "HAITI", currency: "USD" },
    { country: "HEARD ISLAND AND McDONALD ISLANDS", currency: "AUD" },
    { country: "HOLY SEE (THE)", currency: "EUR" },
    { country: "HONDURAS", currency: "HNL" },
    { country: "HONG KONG", currency: "HKD" },
    { country: "HUNGARY", currency: "HUF" },
    { country: "ICELAND", currency: "ISK" },
    { country: "INDIA", currency: "INR" },
    { country: "INDONESIA", currency: "IDR" },
    { country: "INTERNATIONAL MONETARY FUND (IMF)", currency: "XDR" },
    { country: "IRAN (ISLAMIC REPUBLIC OF)", currency: "IRR" },
    { country: "IRAQ", currency: "IQD" },
    { country: "IRELAND", currency: "EUR" },
    { country: "ISLE OF MAN", currency: "GBP" },
    { country: "ISRAEL", currency: "ILS" },
    { country: "ITALY", currency: "EUR" },
    { country: "JAMAICA", currency: "JMD" },
    { country: "JAPAN", currency: "JPY" },
    { country: "JERSEY", currency: "GBP" },
    { country: "JORDAN", currency: "JOD" },
    { country: "KAZAKHSTAN", currency: "KZT" },
    { country: "KENYA", currency: "KES" },
    { country: "KIRIBATI", currency: "AUD" },
    { country: "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)", currency: "KPW" },
    { country: "KOREA (THE REPUBLIC OF)", currency: "KRW" },
    { country: "KUWAIT", currency: "KWD" },
    { country: "KYRGYZSTAN", currency: "KGS" },
    { country: "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)", currency: "LAK" },
    { country: "LATVIA", currency: "EUR" },
    { country: "LEBANON", currency: "LBP" },
    { country: "LESOTHO", currency: "LSL" },
    { country: "LESOTHO", currency: "ZAR" },
    { country: "LIBERIA", currency: "LRD" },
    { country: "LIBYA", currency: "LYD" },
    { country: "LIECHTENSTEIN", currency: "CHF" },
    { country: "LITHUANIA", currency: "EUR" },
    { country: "LUXEMBOURG", currency: "EUR" },
    { country: "MACAO", currency: "MOP" },
    { country: "MADAGASCAR", currency: "MGA" },
    { country: "MALAWI", currency: "MWK" },
    { country: "MALAYSIA", currency: "MYR" },
    { country: "MALDIVES", currency: "MVR" },
    { country: "MALI", currency: "XOF" },
    { country: "MALTA", currency: "EUR" },
    { country: "MARSHALL ISLANDS (THE)", currency: "USD" },
    { country: "MARTINIQUE", currency: "EUR" },
    { country: "MAURITANIA", currency: "MRU" },
    { country: "MAURITIUS", currency: "MUR" },
    { country: "MAYOTTE", currency: "EUR" },
    { country: "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP", currency: "XUA" },
    { country: "MEXICO", currency: "MXN" },
    { country: "MEXICO", currency: "MXV" },
    { country: "MICRONESIA (FEDERATED STATES OF)", currency: "USD" },
    { country: "MOLDOVA (THE REPUBLIC OF)", currency: "MDL" },
    { country: "MONACO", currency: "EUR" },
    { country: "MONGOLIA", currency: "MNT" },
    { country: "MONTENEGRO", currency: "EUR" },
    { country: "MONTSERRAT", currency: "XCD" },
    { country: "MOROCCO", currency: "MAD" },
    { country: "MOZAMBIQUE", currency: "MZN" },
    { country: "MYANMAR", currency: "MMK" },
    { country: "NAMIBIA", currency: "NAD" },
    { country: "NAMIBIA", currency: "ZAR" },
    { country: "NAURU", currency: "AUD" },
    { country: "NEPAL", currency: "NPR" },
    { country: "NETHERLANDS (THE)", currency: "EUR" },
    { country: "NEW CALEDONIA", currency: "XPF" },
    { country: "NEW ZEALAND", currency: "NZD" },
    { country: "NICARAGUA", currency: "NIO" },
    { country: "NIGER (THE)", currency: "XOF" },
    { country: "NIGERIA", currency: "NGN" },
    { country: "NIUE", currency: "NZD" },
    { country: "NORFOLK ISLAND", currency: "AUD" },
    { country: "NORTHERN MARIANA ISLANDS (THE)", currency: "USD" },
    { country: "NORWAY", currency: "NOK" },
    { country: "OMAN", currency: "OMR" },
    { country: "PAKISTAN", currency: "PKR" },
    { country: "PALAU", currency: "USD" },
    { country: "PALESTINE, STATE OF", currency: "" },
    { country: "PANAMA", currency: "PAB" },
    { country: "PANAMA", currency: "USD" },
    { country: "PAPUA NEW GUINEA", currency: "PGK" },
    { country: "PARAGUAY", currency: "PYG" },
    { country: "PERU", currency: "PEN" },
    { country: "PHILIPPINES (THE)", currency: "PHP" },
    { country: "PITCAIRN", currency: "NZD" },
    { country: "POLAND", currency: "PLN" },
    { country: "PORTUGAL", currency: "EUR" },
    { country: "PUERTO RICO", currency: "USD" },
    { country: "QATAR", currency: "QAR" },
    { country: "REPUBLIC OF NORTH MACEDONIA", currency: "MKD" },
    { country: "ROMANIA", currency: "RON" },
    { country: "RUSSIAN FEDERATION (THE)", currency: "RUB" },
    { country: "RWANDA", currency: "RWF" },
    { country: "RÉUNION", currency: "EUR" },
    { country: "SAINT BARTHÉLEMY", currency: "EUR" },
    { country: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", currency: "SHP" },
    { country: "SAINT KITTS AND NEVIS", currency: "XCD" },
    { country: "SAINT LUCIA", currency: "XCD" },
    { country: "SAINT MARTIN (FRENCH PART)", currency: "EUR" },
    { country: "SAINT PIERRE AND MIQUELON", currency: "EUR" },
    { country: "SAINT VINCENT AND THE GRENADINES", currency: "XCD" },
    { country: "SAMOA", currency: "WST" },
    { country: "SAN MARINO", currency: "EUR" },
    { country: "SAO TOME AND PRINCIPE", currency: "STN" },
    { country: "SAUDI ARABIA", currency: "SAR" },
    { country: "SENEGAL", currency: "XOF" },
    { country: "SERBIA", currency: "RSD" },
    { country: "SEYCHELLES", currency: "SCR" },
    { country: "SIERRA LEONE", currency: "SLL" },
    { country: "SINGAPORE", currency: "SGD" },
    { country: "SINT MAARTEN (DUTCH PART)", currency: "ANG" },
    { country: "SLOVAKIA", currency: "EUR" },
    { country: "SLOVENIA", currency: "EUR" },
    { country: "SOLOMON ISLANDS", currency: "SBD" },
    { country: "SOMALIA", currency: "SOS" },
    { country: "SOUTH AFRICA", currency: "ZAR" },
    { country: "SOUTH SUDAN", currency: "SSP" },
    { country: "SPAIN", currency: "EUR" },
    { country: "SRI LANKA", currency: "LKR" },
    { country: "SUDAN (THE)", currency: "SDG" },
    { country: "SURINAME", currency: "SRD" },
    { country: "SVALBARD AND JAN MAYEN", currency: "NOK" },
    { country: "SWAZILAND", currency: "SZL" },
    { country: "SWEDEN", currency: "SEK" },
    { country: "SWITZERLAND", currency: "CHE" },
    { country: "SWITZERLAND", currency: "CHF" },
    { country: "SWITZERLAND", currency: "CHW" },
    { country: "SYRIAN ARAB REPUBLIC", currency: "SYP" },
    { country: "TAIWAN (PROVINCE OF CHINA)", currency: "TWD" },
    { country: "TAJIKISTAN", currency: "TJS" },
    { country: "TANZANIA, UNITED REPUBLIC OF", currency: "TZS" },
    { country: "THAILAND", currency: "THB" },
    { country: "TIMOR-LESTE", currency: "USD" },
    { country: "TOGO", currency: "XOF" },
    { country: "TOKELAU", currency: "NZD" },
    { country: "TONGA", currency: "TOP" },
    { country: "TRINIDAD AND TOBAGO", currency: "TTD" },
    { country: "TUNISIA", currency: "TND" },
    { country: "TURKEY", currency: "TRY" },
    { country: "TURKMENISTAN", currency: "TMT" },
    { country: "TURKS AND CAICOS ISLANDS (THE)", currency: "USD" },
    { country: "TUVALU", currency: "AUD" },
    { country: "UGANDA", currency: "UGX" },
    { country: "UKRAINE", currency: "UAH" },
    { country: "UNITED ARAB EMIRATES (THE)", currency: "AED" },
    { country: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)", currency: "GBP" },
    { country: "UNITED STATES MINOR OUTLYING ISLANDS (THE)", currency: "USD" },
    { country: "UNITED STATES OF AMERICA (THE)", currency: "USD" },
    { country: "UNITED STATES OF AMERICA (THE)", currency: "USN" },
    { country: "URUGUAY", currency: "UYI" },
    { country: "URUGUAY", currency: "UYU" },
    { country: "UZBEKISTAN", currency: "UZS" },
    { country: "VANUATU", currency: "VUV" },
    { country: "VENEZUELA (BOLIVARIAN REPUBLIC OF)", currency: "VEF" },
    { country: "VIET NAM", currency: "VND" },
    { country: "VIRGIN ISLANDS (BRITISH)", currency: "USD" },
    { country: "VIRGIN ISLANDS (U.S.)", currency: "USD" },
    { country: "WALLIS AND FUTUNA", currency: "XPF" },
    { country: "WESTERN SAHARA", currency: "MAD" },
    { country: "YEMEN", currency: "YER" },
    { country: "ZAMBIA", currency: "ZMW" },
    { country: "ZIMBABWE", currency: "ZWL" },
    { country: "ÅLAND ISLANDS", currency: "EUR" },
]